"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Sparkles, Zap, Compass, Archive, Brain, Layers, Palette, Feather } from "lucide-react"
import { cn } from "@/lib/utils"

export function SigilMatchCoreSection() {
  const capabilities = [
    {
      icon: Layers,
      title: "Deep Genre Resonance",
      description:
        "Leverages the Howlin Taxonomy to construct a nuanced Genre Stack, revealing the true lineage and influences within a track.",
      color: "text-purple-400",
    },
    {
      icon: Palette, // Representing emotional colors/palette
      title: "Emotional Cartography",
      description:
        "Maps the artifact's emotional landscape, plotting its valence, arousal, and other affective dimensions onto precise coordinates.",
      color: "text-sky-400",
    },
    {
      icon: Feather, // Representing poetic/light touch
      title: "Poetic Essence Distillation",
      description: "Generates evocative textual blurbs that capture the thematic and atmospheric core of the music.",
      color: "text-emerald-400",
    },
    {
      icon: Archive,
      title: "Vault Attunement",
      description:
        "Assesses an artifact's alignment with the sacred frequencies of 'The Vault', determining its eligibility for this curated collection.",
      color: "text-amber-400",
    },
  ]

  const interactions = [
    {
      icon: Compass,
      name: "Sonic Radar",
      detail: "Fuels discovery with rich data for hyper-personalized recommendations.",
    },
    { icon: Zap, name: "Ritual Chamber", detail: "Guides selection of potent artifacts for Ritual Mixes." },
    {
      icon: Archive,
      name: "Artifact Vault",
      detail: "Acts as the gatekeeper, identifying tracks worthy of preservation.",
    },
    {
      icon: Brain,
      name: "Decision Nexus",
      detail: "Provides critical features for intelligent scoring and weighting.",
    },
  ]

  return (
    <section className="py-16 px-4 bg-black/30 backdrop-blur-sm">
      <div className="container mx-auto">
        <Card className="bg-card/70 border-primary/20 shadow-xl">
          <CardHeader className="text-center">
            <Sparkles className="w-12 h-12 mx-auto mb-4 text-primary animate-pulse" />
            <CardTitle className="text-3xl sm:text-4xl font-bold font-orbitron text-primary responsive-text-overlay">
              SigilMatch Core
            </CardTitle>
            <p className="text-lg text-slate-300 font-poetic mt-2 max-w-3xl mx-auto responsive-text-overlay">
              Decoding Sonic Signatures & Unveiling Energetic Essences
            </p>
          </CardHeader>
          <CardContent className="space-y-12">
            <p className="text-center text-slate-300 leading-relaxed max-w-4xl mx-auto text-base sm:text-lg responsive-text-overlay">
              At the heart of Howlin Mold lies the SigilMatch Core, a sophisticated engine dedicated to transmuting raw
              sonic artifacts into profound energetic signatures. It delves beyond conventional analysis, seeking the
              unique essence of each track to generate its 'Sigil Overlay' – a multi-faceted representation of its soul.
            </p>

            <div>
              <h3 className="text-2xl font-orbitron text-center mb-8 text-slate-100 responsive-text-overlay">
                Key Capabilities
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {capabilities.map((cap, index) => {
                  const Icon = cap.icon
                  return (
                    <div
                      key={index}
                      className="p-6 rounded-lg bg-black/40 border border-primary/10 hover:border-primary/30 transition-all duration-300"
                    >
                      <div className="flex items-center mb-3">
                        <Icon className={cn("w-7 h-7 mr-3", cap.color)} />
                        <h4 className="text-xl font-semibold font-orbitron text-slate-200">{cap.title}</h4>
                      </div>
                      <p className="text-sm text-slate-400 leading-relaxed">{cap.description}</p>
                    </div>
                  )
                })}
              </div>
            </div>

            <div>
              <h3 className="text-2xl font-orbitron text-center mb-8 text-slate-100 responsive-text-overlay">
                Ecosystem Synergy
              </h3>
              <p className="text-center text-slate-400 mb-8 max-w-2xl mx-auto responsive-text-overlay">
                The insights generated by SigilMatch Core are the lifeblood of the Howlin Mold ecosystem:
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {interactions.map((interaction, index) => {
                  const Icon = interaction.icon
                  return (
                    <div
                      key={index}
                      className="p-4 rounded-md bg-black/30 border border-primary/10 text-center group hover:bg-primary/5 transition-colors"
                    >
                      <Icon className="w-8 h-8 mx-auto mb-2 text-primary/70 group-hover:text-primary transition-colors" />
                      <h5 className="text-md font-semibold text-slate-200 mb-1">{interaction.name}</h5>
                      <p className="text-xs text-slate-400">{interaction.detail}</p>
                    </div>
                  )
                })}
              </div>
            </div>

            <div className="text-center pt-6">
              <h3 className="text-xl font-orbitron text-primary mb-3 responsive-text-overlay">
                The Alchemical Transformation
              </h3>
              <p className="text-slate-300 leading-relaxed max-w-3xl mx-auto responsive-text-overlay">
                SigilMatch Core transforms music from mere audio into a tangible, navigable energetic pattern. This
                enables deeper connection, profound understanding, and a truly personalized journey through the sonic
                ether, empowering you to curate your reality with intention.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  )
}
