export interface Artifact {
  id: string
  name: string
  artist: string
  description: string
  tags: string[]
  price?: number
  imageUrl?: string
  audioUrl?: string
  genre?: string
  year?: number
  duration?: string
  bpm?: number
  key?: string
  energy?: number
  danceability?: number
  valence?: number
  acousticness?: number
  instrumentalness?: number
  liveness?: number
  speechiness?: number
  popularity?: number
  explicit?: boolean
  preview_url?: string
  external_urls?: {
    spotify?: string
  }
}

export const mockArtifacts: Artifact[] = [
  {
    id: "1",
    name: "Ethereal Drift",
    artist: "Cosmic Wanderer",
    description: "A journey through ambient soundscapes that transport you to otherworldly realms.",
    tags: ["ambient", "ethereal", "cosmic", "meditative"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Ambient",
    year: 2023,
    duration: "4:32",
    bpm: 72,
    key: "A Minor",
    energy: 0.2,
    danceability: 0.1,
    valence: 0.3,
    acousticness: 0.9,
    instrumentalness: 0.95,
    liveness: 0.1,
    speechiness: 0.02,
    popularity: 65,
    explicit: false,
  },
  {
    id: "2",
    name: "Neon Pulse",
    artist: "Synthwave Prophet",
    description: "Retro-futuristic beats that capture the essence of 80s cyberpunk aesthetics.",
    tags: ["synthwave", "retro", "cyberpunk", "electronic"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Synthwave",
    year: 2023,
    duration: "3:45",
    bpm: 128,
    key: "C# Minor",
    energy: 0.8,
    danceability: 0.7,
    valence: 0.6,
    acousticness: 0.1,
    instrumentalness: 0.8,
    liveness: 0.15,
    speechiness: 0.05,
    popularity: 78,
    explicit: false,
  },
  {
    id: "3",
    name: "Forest Whispers",
    artist: "Nature's Echo",
    description: "Organic sounds blended with subtle electronic textures, evoking deep forest mysteries.",
    tags: ["organic", "nature", "mysterious", "ambient"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Organic Ambient",
    year: 2023,
    duration: "6:18",
    bpm: 65,
    key: "F Major",
    energy: 0.3,
    danceability: 0.2,
    valence: 0.4,
    acousticness: 0.8,
    instrumentalness: 0.9,
    liveness: 0.2,
    speechiness: 0.03,
    popularity: 52,
    explicit: false,
  },
  {
    id: "4",
    name: "Digital Shaman",
    artist: "Techno Mystic",
    description: "Hypnotic techno rhythms infused with shamanic elements and tribal percussion.",
    tags: ["techno", "shamanic", "tribal", "hypnotic"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Techno",
    year: 2023,
    duration: "7:22",
    bpm: 135,
    key: "E Minor",
    energy: 0.9,
    danceability: 0.85,
    valence: 0.5,
    acousticness: 0.2,
    instrumentalness: 0.7,
    liveness: 0.3,
    speechiness: 0.1,
    popularity: 71,
    explicit: false,
  },
  {
    id: "5",
    name: "Quantum Entanglement",
    artist: "Particle Physics",
    description: "Complex polyrhythms and intricate sound design exploring the mysteries of quantum mechanics.",
    tags: ["experimental", "complex", "scientific", "polyrhythmic"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Experimental Electronic",
    year: 2023,
    duration: "5:47",
    bpm: 142,
    key: "B♭ Minor",
    energy: 0.7,
    danceability: 0.4,
    valence: 0.3,
    acousticness: 0.1,
    instrumentalness: 0.95,
    liveness: 0.1,
    speechiness: 0.02,
    popularity: 43,
    explicit: false,
  },
  {
    id: "6",
    name: "Solar Wind",
    artist: "Astral Navigator",
    description: "Expansive drones and celestial harmonies that capture the vastness of space.",
    tags: ["drone", "space", "celestial", "expansive"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Space Ambient",
    year: 2023,
    duration: "8:15",
    bpm: 60,
    key: "D Major",
    energy: 0.25,
    danceability: 0.1,
    valence: 0.4,
    acousticness: 0.7,
    instrumentalness: 0.98,
    liveness: 0.05,
    speechiness: 0.01,
    popularity: 38,
    explicit: false,
  },
  {
    id: "7",
    name: "Urban Decay",
    artist: "Industrial Prophet",
    description: "Gritty industrial sounds mixed with haunting melodies, reflecting urban desolation.",
    tags: ["industrial", "dark", "urban", "haunting"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Dark Industrial",
    year: 2023,
    duration: "4:58",
    bpm: 110,
    key: "G Minor",
    energy: 0.8,
    danceability: 0.5,
    valence: 0.2,
    acousticness: 0.1,
    instrumentalness: 0.6,
    liveness: 0.2,
    speechiness: 0.15,
    popularity: 59,
    explicit: true,
  },
  {
    id: "8",
    name: "Crystalline Dreams",
    artist: "Lucid Architect",
    description: "Delicate crystalline textures and dreamy progressions that blur the line between sleep and waking.",
    tags: ["dreamy", "crystalline", "delicate", "lucid"],
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    imageUrl: "/placeholder.svg?height=300&width=300",
    genre: "Dream Pop Electronic",
    year: 2023,
    duration: "5:23",
    bpm: 85,
    key: "A Major",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.7,
    acousticness: 0.4,
    instrumentalness: 0.8,
    liveness: 0.1,
    speechiness: 0.05,
    popularity: 67,
    explicit: false,
  },
]
