-- Create user_snapshots table
create table public.user_snapshots (
  id bigint generated by default as identity,
  user_id uuid not null references auth.users on delete cascade,
  name text not null,
  description text,
  tags text[],
  state jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,

  primary key (id),
  unique(user_id, name)
);

comment on table public.user_snapshots is 'Stores synthesizer state snapshots for users.';

-- Function to set updated_at timestamp
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Trigger to update the updated_at column on user_snapshots
create trigger handle_snapshot_updated_at
before update on public.user_snapshots
for each row
execute procedure public.set_updated_at();
